controller_list:
  - name: fake_arm_l_controller
    type: $(arg fake_execution_type)
    joints:
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l
  - name: fake_arm_r_controller
    type: $(arg fake_execution_type)
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
initial:  # Define initial robot poses per group
  - group: arm_l
    pose: start_l
  - group: arm_r
    pose: start_r